<?php
require_once '../config.php';
require_once 'email.php';

if (isLoggedIn()) {
    redirect('dashboard.php');
}

$errors = [];
$success = '';
$token = $_GET['token'] ?? '';
$user = null;
$show_email_form = !$token; // Show email form if no token

if ($token) {
    // Verify token
    $stmt = $pdo->prepare("
        SELECT prt.*, u.username, u.email
        FROM password_reset_tokens prt
        JOIN users u ON prt.user_id = u.id
        WHERE prt.token = ? AND prt.used = FALSE AND prt.expires_at > NOW()
    ");
    $stmt->execute([$token]);
    $user = $stmt->fetch();

    if (!$user) {
        $errors[] = 'This password reset link is invalid or has expired. Please request a new one.';
        $show_email_form = true; // Fall back to email form
    }
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (isset($_POST['request_reset'])) {
        // Handle identifier form submission (email, username, or phone number)
        $identifier = sanitize($_POST['identifier'] ?? '');

        if (empty($identifier)) {
            $errors[] = 'Please enter your email address, username, or phone number.';
        } else {
            // Check if identifier exists in database (email, username, or phone_number)
            $stmt = $pdo->prepare("SELECT id, username, email FROM users WHERE email = ? OR username = ? OR phone_number = ?");
            $stmt->execute([$identifier, $identifier, $identifier]);
            $user_check = $stmt->fetch();

            if (!$user_check) {
                $errors[] = 'No account found with this identifier (email, username, or phone number).';
            } else {
                // Generate secure token
                $token = bin2hex(random_bytes(32));

                // Set expiration (24 hours from now)
                $expires_at = date('Y-m-d H:i:s', strtotime('+24 hours'));

                // Delete any existing tokens for this user
                $stmt = $pdo->prepare("DELETE FROM password_reset_tokens WHERE user_id = ?");
                $stmt->execute([$user_check['id']]);

                // Insert new token
                $stmt = $pdo->prepare("INSERT INTO password_reset_tokens (user_id, token, expires_at) VALUES (?, ?, ?)");
                if ($stmt->execute([$user_check['id'], $token, $expires_at])) {
                    // Send email
                    $reset_link = BASE_URL . "/reset_password.php?token=" . $token;

                    // Generate random password
                    $newPassword = generateRandomPassword(10);

                    // Hash the new password
                    $hashedPassword = password_hash($newPassword, PASSWORD_DEFAULT);

                    // Update user password in database
                    $stmt = $pdo->prepare("UPDATE users SET password = ? WHERE id = ?");
                    if ($stmt->execute([$hashedPassword, $user_check['id']])) {
                        // Send auto-generated password via email if user has email, otherwise display it
                        if (!empty($user_check['email'])) {
                            if (sendAutoGeneratedPassword($user_check['email'], $newPassword)) {
                                $success = "A new password has been generated and sent to your email address. Please check your inbox and use the new password to log in.";
                            } else {
                                $errors[] = 'Failed to send the new password email. Please try again later.';
                                // Display the new password as fallback
                                $success = "A new password has been generated for your account. Your new password is: <strong>$newPassword</strong>. Please save it and use it to <a href='login.php' class='alert-link'>login</a>.";
                            }
                        } else {
                            $success = "A new password has been generated for your account. Your new password is: <strong>$newPassword</strong>. Please save it and use it to <a href='login.php' class='alert-link'>login</a>.";
                        }
                    } else {
                        $errors[] = 'Failed to update password. Please try again.';
                    }
                } else {
                    $errors[] = 'Failed to generate reset token. Please try again.';
                }
            }
        }
    } elseif (isset($_POST['reset_password']) && $user) {
        // Handle password reset form submission
        $password = $_POST['password'] ?? '';
        $confirm_password = $_POST['confirm_password'] ?? '';

        if (empty($password) || empty($confirm_password)) {
            $errors[] = 'Please fill in all fields.';
        } elseif ($password !== $confirm_password) {
            $errors[] = 'Passwords do not match.';
        } elseif (strlen($password) < 6) {
            $errors[] = 'Password must be at least 6 characters long.';
        } else {
            // Hash new password
            $hashed_password = password_hash($password, PASSWORD_DEFAULT);

            // Update user password
            $stmt = $pdo->prepare("UPDATE users SET password = ? WHERE id = ?");
            if ($stmt->execute([$hashed_password, $user['user_id']])) {
                // Mark token as used
                $stmt = $pdo->prepare("UPDATE password_reset_tokens SET used = TRUE WHERE token = ?");
                $stmt->execute([$token]);

                $success = 'Password reset successfully! You can now <a href="login.php" class="alert-link">login</a> with your new password.';
            } else {
                $errors[] = 'Failed to reset password. Please try again.';
            }
        }
    }
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reset Password - <?php echo SITE_NAME; ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <style>
        :root {
            --primary: #1a5276;
            --secondary: #f39c12;
            --accent: #e74c3c;
            --light: #ecf0f1;
            --dark: #2c3e50;
            --success: #27ae60;
        }

        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: var(--light);
            color: var(--dark);
            overflow-x: hidden;
            min-height: 100vh;
            display: flex;
            align-items: center;
        }

        /* Animated Background */
        .background-container {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            z-index: -1;
            overflow: hidden;
        }

        .background-slide {
            position: absolute;
            width: 100%;
            height: 100%;
            background-size: cover;
            background-position: center;
            opacity: 0;
            animation: backgroundAnimation 24s infinite;
        }

        .slide-1 {
            background-image: url('https://images.unsplash.com/photo-1541888946425-d81bb19240f5?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80');
            animation-delay: 0s;
        }

        .slide-2 {
            background-image: url('https://images.unsplash.com/photo-1504307651254-35680f356dfd?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80');
            animation-delay: 6s;
        }

        .slide-3 {
            background-image: url('https://images.unsplash.com/photo-1541140532154-b024d705b90a?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80');
            animation-delay: 12s;
        }

        .slide-4 {
            background-image: url('https://images.unsplash.com/photo-1582139329536-e7284fece509?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80');
            animation-delay: 18s;
        }

        @keyframes backgroundAnimation {
            0% { opacity: 0; }
            10% { opacity: 1; }
            25% { opacity: 1; }
            35% { opacity: 0; }
            100% { opacity: 0; }
        }

        /* Reset Password Container */
        .reset-container {
            width: 100%;
            max-width: 450px;
            margin: 0 auto;
            animation: fadeInUp 0.8s ease;
        }

        .reset-card {
            border: none;
            border-radius: 20px;
            overflow: hidden;
            box-shadow: 0 20px 60px rgba(0,0,0,0.2);
            background: white;
            backdrop-filter: blur(10px);
        }

        .reset-header {
            background: linear-gradient(135deg, var(--success), #2ecc71);
            color: white;
            padding: 30px;
            text-align: center;
            position: relative;
            overflow: hidden;
        }

        .reset-header::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="none"><path d="M0,0 L100,0 L100,100 Z" fill="%23ffffff" opacity="0.1"/></svg>');
            background-size: cover;
        }

        .reset-title {
            font-size: 2.2rem;
            font-weight: 800;
            margin-bottom: 10px;
            position: relative;
            z-index: 1;
        }

        .reset-subtitle {
            font-size: 1rem;
            opacity: 0.9;
            position: relative;
            z-index: 1;
        }

        .reset-body {
            padding: 40px;
        }

        /* Form Styling */
        .form-label {
            font-weight: 600;
            color: var(--dark);
            margin-bottom: 8px;
        }

        .input-group {
            position: relative;
            margin-bottom: 25px;
        }

        .form-control {
            border: 2px solid #e9ecef;
            border-radius: 12px;
            padding: 15px 20px 15px 50px;
            font-size: 1rem;
            transition: all 0.3s;
            background: #f8f9fa;
        }

        .form-control:focus {
            border-color: var(--success);
            box-shadow: 0 0 0 0.25rem rgba(39, 174, 96, 0.25);
            background: white;
        }

        .input-icon {
            position: absolute;
            left: 20px;
            top: 50%;
            transform: translateY(-50%);
            color: var(--success);
            font-size: 1.2rem;
            z-index: 5;
        }

        .btn-update {
            background: linear-gradient(135deg, var(--success), #2ecc71);
            border: none;
            color: white;
            font-weight: 600;
            padding: 15px;
            border-radius: 12px;
            transition: all 0.3s ease;
            box-shadow: 0 4px 15px rgba(39, 174, 96, 0.4);
            width: 100%;
            font-size: 1.1rem;
            margin-top: 10px;
        }

        .btn-update:hover {
            transform: translateY(-2px);
            box-shadow: 0 6px 20px rgba(39, 174, 96, 0.6);
        }

        .btn-update:active {
            transform: translateY(0);
        }

        .btn-reset {
            background: linear-gradient(135deg, var(--primary), var(--dark));
            border: none;
            color: white;
            font-weight: 600;
            padding: 15px;
            border-radius: 12px;
            transition: all 0.3s ease;
            box-shadow: 0 4px 15px rgba(26, 82, 118, 0.4);
            width: 100%;
            font-size: 1.1rem;
            margin-top: 10px;
        }

        .btn-reset:hover {
            transform: translateY(-2px);
            box-shadow: 0 6px 20px rgba(26, 82, 118, 0.6);
        }

        .btn-reset:active {
            transform: translateY(0);
        }

        /* Password Strength Indicator */
        .password-strength {
            height: 5px;
            border-radius: 5px;
            margin-top: 8px;
            background: #e9ecef;
            overflow: hidden;
        }

        .strength-bar {
            height: 100%;
            width: 0;
            border-radius: 5px;
            transition: all 0.3s ease;
        }

        .strength-weak {
            background: #e74c3c;
            width: 33%;
        }

        .strength-medium {
            background: #f39c12;
            width: 66%;
        }

        .strength-strong {
            background: #27ae60;
            width: 100%;
        }

        .strength-text {
            font-size: 0.85rem;
            margin-top: 5px;
            text-align: right;
        }

        /* Password Toggle */
        .password-toggle {
            position: absolute;
            right: 20px;
            top: 50%;
            transform: translateY(-50%);
            background: none;
            border: none;
            color: #6c757d;
            cursor: pointer;
            z-index: 10;
        }

        .password-toggle:hover {
            color: var(--success);
        }

        /* Alert Styling */
        .alert {
            border: none;
            border-radius: 12px;
            padding: 15px 20px;
            margin-bottom: 25px;
        }

        .alert-danger {
            background: rgba(231, 76, 60, 0.1);
            color: #c0392b;
            border-left: 4px solid var(--accent);
        }

        .alert-success {
            background: rgba(39, 174, 96, 0.1);
            color: #27ae60;
            border-left: 4px solid var(--success);
        }

        .alert ul {
            margin-bottom: 0;
            padding-left: 20px;
        }

        /* Links */
        .reset-links {
            text-align: center;
            margin-top: 25px;
            padding-top: 20px;
            border-top: 1px solid #e9ecef;
        }

        .reset-link {
            color: var(--success);
            text-decoration: none;
            font-weight: 600;
            transition: all 0.3s;
            display: inline-flex;
            align-items: center;
        }

        .reset-link:hover {
            color: var(--primary);
            transform: translateX(5px);
        }

        .reset-link i {
            margin-right: 8px;
        }

        /* Animation */
        @keyframes fadeInUp {
            from {
                opacity: 0;
                transform: translateY(30px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }

        /* Responsive */
        @media (max-width: 576px) {
            .reset-container {
                padding: 0 20px;
            }

            .reset-body {
                padding: 30px 25px;
            }

            .reset-header {
                padding: 25px;
            }

            .reset-title {
                font-size: 1.8rem;
            }
        }
    </style>
</head>
<body>
    <!-- Animated Background -->
    <div class="background-container">
        <div class="background-slide slide-1"></div>
        <div class="background-slide slide-2"></div>
        <div class="background-slide slide-3"></div>
        <div class="background-slide slide-4"></div>
    </div>

    <!-- Reset Password Container -->
    <div class="container">
        <div class="reset-container">
            <div class="reset-card">
                <div class="reset-header">
                    <h1 class="reset-title"><?php echo $show_email_form ? 'Reset Password' : 'New Password'; ?></h1>
                    <p class="reset-subtitle"><?php echo $show_email_form ? 'Enter your email address, username, or phone number' : 'Enter your new password below'; ?></p>
                </div>
                <div class="reset-body">
                    <?php if (!empty($errors)): ?>
                        <div class="alert alert-danger">
                            <ul class="mb-0">
                                <?php foreach ($errors as $error): ?>
                                    <li><?php echo $error; ?></li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    <?php endif; ?>

                    <?php if (!empty($success)): ?>
                        <div class="alert alert-success"><?php echo $success; ?></div>
                    <?php endif; ?>

                    <?php if ($show_email_form): ?>
                        <!-- Email Form -->
                        <form method="POST">
                            <input type="hidden" name="request_reset" value="1">
                            <div class="input-group">
                                <i class="fas fa-user input-icon"></i>
                                <input type="text" class="form-control" id="identifier" name="identifier" placeholder="Enter your email, username, or phone number" required>
                            </div>

                            <button type="submit" class="btn-reset">
                                <i class="fas fa-paper-plane me-2"></i> Send Reset Link
                            </button>
                        </form>
                    <?php elseif ($user): ?>
                        <!-- Password Reset Form -->
                        <div class="mb-3">
                            <p class="text-muted">Resetting password for: <strong><?php echo htmlspecialchars($user['email']); ?></strong></p>
                        </div>

                        <form method="POST" id="resetForm" novalidate>
                            <input type="hidden" name="reset_password" value="1">
                            <div class="input-group">
                                <i class="fas fa-lock input-icon"></i>
                                <input type="password" class="form-control" id="password" name="password" placeholder="Enter new password" required minlength="6">
                                <button type="button" class="password-toggle" id="togglePassword">
                                    <i class="fas fa-eye"></i>
                                </button>
                                <div class="password-strength">
                                    <div class="strength-bar" id="passwordStrength"></div>
                                </div>
                                <div class="strength-text" id="passwordText">Password strength</div>
                            </div>

                            <div class="input-group">
                                <i class="fas fa-lock input-icon"></i>
                                <input type="password" class="form-control" id="confirm_password" name="confirm_password" placeholder="Confirm new password" required>
                                <button type="button" class="password-toggle" id="toggleConfirmPassword">
                                    <i class="fas fa-eye"></i>
                                </button>
                                <div class="invalid-feedback">Passwords must match.</div>
                            </div>

                            <button type="submit" class="btn-update">
                                <i class="fas fa-key me-2"></i> Update Password
                            </button>
                        </form>
                    <?php endif; ?>

                    <div class="reset-links">
                        <a href="login.php" class="reset-link">
                            <i class="fas fa-sign-in-alt"></i> Back to Login
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            <?php if ($user && !$show_email_form): ?>
            // Password toggle functionality
            const togglePassword = document.getElementById('togglePassword');
            const passwordInput = document.getElementById('password');
            const toggleConfirmPassword = document.getElementById('toggleConfirmPassword');
            const confirmPasswordInput = document.getElementById('confirm_password');

            togglePassword.addEventListener('click', function() {
                const type = passwordInput.getAttribute('type') === 'password' ? 'text' : 'password';
                passwordInput.setAttribute('type', type);

                const icon = this.querySelector('i');
                if (type === 'password') {
                    icon.classList.remove('fa-eye-slash');
                    icon.classList.add('fa-eye');
                } else {
                    icon.classList.remove('fa-eye');
                    icon.classList.add('fa-eye-slash');
                }
            });

            toggleConfirmPassword.addEventListener('click', function() {
                const type = confirmPasswordInput.getAttribute('type') === 'password' ? 'text' : 'password';
                confirmPasswordInput.setAttribute('type', type);

                const icon = this.querySelector('i');
                if (type === 'password') {
                    icon.classList.remove('fa-eye-slash');
                    icon.classList.add('fa-eye');
                } else {
                    icon.classList.remove('fa-eye');
                    icon.classList.add('fa-eye-slash');
                }
            });

            // Password strength indicator
            passwordInput.addEventListener('input', function() {
                const password = this.value;
                const strengthBar = document.getElementById('passwordStrength');
                const strengthText = document.getElementById('passwordText');

                // Reset
                strengthBar.className = 'strength-bar';
                strengthBar.style.width = '0';

                if (password.length === 0) {
                    strengthText.textContent = 'Password strength';
                    return;
                }

                // Calculate strength
                let strength = 0;

                // Length check
                if (password.length >= 6) strength += 1;
                if (password.length >= 8) strength += 1;

                // Character variety checks
                if (/[a-z]/.test(password)) strength += 1;
                if (/[A-Z]/.test(password)) strength += 1;
                if (/[0-9]/.test(password)) strength += 1;
                if (/[^a-zA-Z0-9]/.test(password)) strength += 1;

                // Update strength indicator
                if (strength <= 2) {
                    strengthBar.classList.add('strength-weak');
                    strengthText.textContent = 'Weak password';
                    strengthText.style.color = '#e74c3c';
                } else if (strength <= 4) {
                    strengthBar.classList.add('strength-medium');
                    strengthText.textContent = 'Medium password';
                    strengthText.style.color = '#f39c12';
                } else {
                    strengthBar.classList.add('strength-strong');
                    strengthText.textContent = 'Strong password';
                    strengthText.style.color = '#27ae60';
                }
            });

            // Form validation
            const form = document.getElementById('resetForm');

            form.addEventListener('submit', function(event) {
                if (!form.checkValidity()) {
                    event.preventDefault();
                    event.stopPropagation();
                }

                // Check if passwords match
                const password = document.getElementById('password').value;
                const confirmPassword = document.getElementById('confirm_password').value;

                if (password !== confirmPassword) {
                    event.preventDefault();
                    event.stopPropagation();
                    document.getElementById('confirm_password').classList.add('is-invalid');
                } else {
                    document.getElementById('confirm_password').classList.remove('is-invalid');
                }

                form.classList.add('was-validated');
            });

            // Real-time password match validation
            confirmPasswordInput.addEventListener('input', function() {
                const password = passwordInput.value;
                const confirmPassword = this.value;

                if (confirmPassword && password !== confirmPassword) {
                    this.classList.add('is-invalid');
                } else {
                    this.classList.remove('is-invalid');
                }
            });

            // Auto-focus password field
            document.getElementById('password').focus();
            <?php elseif ($show_email_form): ?>
            // Auto-focus identifier field
            document.getElementById('identifier').focus();
            <?php endif; ?>
        });
    </script>
</body>
</html>
